### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter URL: ");
    yylex();
    return 0;
}

int yywrap()
{
    return 1;
}
```
