### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>
#include <string.h>

int max_length = 0;
char longest_word[100];

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter a sentence:\n");

    yylex();

    printf("\nLongest word = %s\n", longest_word);
    printf("Length of longest word = %d\n", max_length);

    return 0;
}

int yywrap()
{
    return 1;
}
``
