### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>
#include <string.h>

char search_word[50];
int count = 0;

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter the word to search: ");
    scanf("%49s", search_word);

    getchar();

    printf("Enter the sentence:\n");

    yylex();

    printf("\nFrequency of \"%s\" = %d\n",
           search_word, count);

    return 0;
}

int yywrap()
{
    return 1;
}
```
