### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>

int yywrap(void);
int yylex(void);

int main()
{
    printf("Enter C program statements:\n");
    yylex();
    return 0;
}

int yywrap()
{
    return 1;
}
```
