### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>

int positive = 0;
int negative = 0;

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter numbers:\n");

    yylex();

    printf("\nNumber of positive numbers = %d\n", positive);
    printf("Number of negative numbers = %d\n", negative);

    return 0;
}

int yywrap()
{
    return 1;
}
```
