### lex.yy.c

```c
/* Generated by Flex */

#include <stdio.h>
#include <stdlib.h>

int num1, num2;

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter mathematical expression: ");
    yylex();
    return 0;
}

int yywrap()
{
    return 1;
}
```
