/* Generated by Flex */

#include <stdio.h>
#include <string.h>

char old_word[50];
char new_word[50];
FILE *output;

int yylex(void);
int yywrap(void);

int main()
{
    printf("Enter word to replace: ");
    scanf("%49s", old_word);

    printf("Enter new word: ");
    scanf("%49s", new_word);

    yyin = fopen("input.txt", "r");
    output = fopen("output.txt", "w");

    if (yyin == NULL)
    {
        printf("Cannot open input.txt\n");
        return 1;
    }

    if (output == NULL)
    {
        printf("Cannot create output.txt\n");
        return 1;
    }

    yylex();

    fclose(yyin);
    fclose(output);

    printf("\nReplacement completed.\n");
    printf("Modified content is stored in output.txt\n");

    return 0;
}

int yywrap()
{
    return 1;
}
